#!/usr/bin/env python3
"""Assemble the capstone PDF report from showcase screenshots.

The report is intentionally NEUTRAL:
  * no repository name / URL
  * no owner name / author
  * no deployment / hosting URLs
  * no real personal data (the showcased CV pool is synthetic)

Screenshots come from the real running application, generated by
scripts/ui_showcase.py.
"""

from __future__ import annotations

import os
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Frame,
    Image,
    PageBreak,
    PageTemplate,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

REPO = Path(__file__).resolve().parent.parent
SHOTS = Path(os.getenv("SHOWCASE_SHOTS", REPO / "artifacts" / "showcase"))
OUT = Path(os.getenv("SHOWCASE_PDF", REPO / "artifacts" / "cvmatcher_capstone_report.pdf"))
OUT.parent.mkdir(parents=True, exist_ok=True)

A4W, A4H = A4

# ---------------------------------------------------------------------------
# Styles
# ---------------------------------------------------------------------------
styles = getSampleStyleSheet()

TITLE = ParagraphStyle(
    "TitleX", parent=styles["Title"], fontSize=26, leading=32, textColor=colors.HexColor("#1a3c6e"),
    alignment=TA_CENTER, spaceAfter=6,
)
SUBTITLE = ParagraphStyle(
    "SubtitleX", parent=styles["Normal"], fontSize=13, leading=18, alignment=TA_CENTER,
    textColor=colors.HexColor("#555555"), spaceAfter=2,
)
H1 = ParagraphStyle("H1X", parent=styles["Heading1"], fontSize=16, leading=20,
                    textColor=colors.HexColor("#1a3c6e"), spaceBefore=8, spaceAfter=8)
H2 = ParagraphStyle("H2X", parent=styles["Heading2"], fontSize=13, leading=17,
                    textColor=colors.HexColor("#2a5a8f"), spaceBefore=6, spaceAfter=6)
BODY = ParagraphStyle("BodyX", parent=styles["BodyText"], fontSize=10, leading=15,
                      alignment=TA_JUSTIFY, spaceAfter=8)
CAP = ParagraphStyle("CapX", parent=styles["BodyText"], fontSize=9, leading=12,
                     textColor=colors.HexColor("#666666"), spaceBefore=2, spaceAfter=4)
SMALL = ParagraphStyle("SmallX", parent=styles["BodyText"], fontSize=8.5, leading=12,
                       textColor=colors.HexColor("#777777"))


def footer(canvas, doc):
    """Neutral page footer: page number only."""
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#999999"))
    canvas.drawCentredString(A4W / 2, 12 * mm, f"Page {doc.page}")
    canvas.setStrokeColor(colors.HexColor("#dddddd"))
    canvas.line(20 * mm, 15 * mm, A4W - 20 * mm, 15 * mm)
    canvas.restoreState()


def build() -> None:
    doc = SimpleDocTemplate(
        str(OUT), pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm, topMargin=20 * mm, bottomMargin=22 * mm,
        title="Capstone Project Report - Agentic RAG CV Expert Matching",
        author="",
    )
    frame = Frame(20 * mm, 22 * mm, A4W - 40 * mm, A4H - 42 * mm, id="main")
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=footer)])

    story: list = []

    # ------------------------------------------------------------------ Cover
    story.append(Spacer(1, 34 * mm))
    story.append(Paragraph("Agentic RAG CV Expertise Matcher", TITLE))
    story.append(Paragraph("Capstone Project Report — Demonstration & Verification", SUBTITLE))
    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph(
        "A retrieval-augmented generation system with a four-agent reasoning pipeline "
        "that ingests CV documents, builds a semantic knowledge base, and answers "
        "natural-language expertise queries with ranked, cited candidates.",
        BODY,
    ))
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph(
        "This report demonstrates the application running end-to-end. Every screenshot "
        "was captured from the live application while it processed a synthetic CV pool "
        "(no real personal data is used in this demonstration).",
        BODY,
    ))

    story.append(Spacer(1, 3 * mm))
    story.append(Paragraph(
        "Contents:  System Overview · Architecture · Features · Verification Record · "
        "Screenshots · Quality & Safety · Evaluation · Limitations & Challenges",
        BODY,
    ))
    story.append(PageBreak())

    # ------------------------------------------------------------- 1 Overview
    story.append(Paragraph("1. System Overview", H1))
    story.append(Paragraph(
        "The application automates the process of matching candidates to job requirements. "
        "A manager uploads a pool of CVs (PDF, TXT, CSV or Excel). The system ingests each "
        "document, splits it into semantically meaningful sections, embeds the sections into "
        "a vector store, and builds a searchable knowledge base. The user then asks natural-"
        "language questions - for example \u201cFind a Java developer with Spring Boot "
        "experience\u201d - and the system returns ranked candidates with match scores, "
        "supporting evidence and source citations.",
        BODY,
    ))
    story.append(Paragraph(
        "The system is built around an explicit four-agent reasoning loop rather than a "
        "single LLM call: a Planner classifies the query and extracts requirements, a "
        "Retriever searches the vector store, a Responder generates the grounded answer, "
        "and a Validator checks answer quality, feeding feedback back to the Responder for "
        "a bounded number of refinement passes.",
        BODY,
    ))

    # ------------------------------------------------------- 2 Architecture
    story.append(Paragraph("2. Architecture", H1))
    story.append(Paragraph(
        "The application follows a cleanly layered architecture:",
        BODY,
    ))
    story.append(Paragraph(
        "<b>Presentation layer</b> - a web frontend (Streamlit) provides the user "
        "interface: Home, Query, Documents, Dashboard and Evaluation pages. The frontend "
        "never holds domain logic; it only talks to the backend over HTTP.",
        BODY,
    ))
    story.append(Paragraph(
        "<b>API layer</b> - a FastAPI service exposes a typed REST API for document "
        "upload/management, query execution, dashboard statistics, key validation, "
        "synthetic-data generation and AI evaluation. It applies request validation, "
        "rate limiting and optional bearer-token authentication, and is protected by "
        "restricted CORS configuration.",
        BODY,
    ))
    story.append(Paragraph(
        "<b>Agent layer</b> - the orchestration pipeline (Planner, Retriever, Responder, "
        "Validator) with an LLM client abstraction that handles transient errors with "
        "exponential backoff and retry. All model names and thresholds come from "
        "configuration, never from code.",
        BODY,
    ))
    story.append(Paragraph(
        "<b>Data layer</b> - ingestion extractors (PDF, TXT, CSV, XLSX), section-aware "
        "chunking, a ChromaDB vector store with cosine similarity, and a guardrail layer "
        "that scans inputs and documents for prompt-injection patterns.",
        BODY,
    ))

    # ----------------------------------------------------------- 3 Features
    story.append(Paragraph("3. Feature Highlights", H1))
    for feat in [
        "Agentic RAG pipeline with Planner \u2192 Retriever \u2192 Responder \u2192 Validator, plus a bounded quality retry loop.",
        "Multi-format ingestion: PDF, TXT, CSV and Excel, with filename/path traversal hardening and per-format extractors.",
        "Section-aware chunking that preserves CV structure (Summary, Skills, Experience, Education) for accurate retrieval.",
        "Semantic vector search with cosine similarity, match scoring (0\u2013100%) and source-document citations in every answer.",
        "Guardrails: prompt-injection scanning at ingestion, out-of-scope query rejection, output validation with evidence-aware retry.",
        "Synthetic data generator (TXT/PDF/CSV) for testing and demonstration without releasing any real personal data.",
        "Reliability controls: transient LLM-error retry with exponential backoff, bounded upload sizes, optional auth and rate limiting.",
        "AI evaluation harness that scores the pipeline against a question set and reports pass rate and failure modes.",
    ]:
        story.append(Paragraph(f"\u2022  {feat}", BODY))

    # ---------------------------------------------------- 4 Verification
    story.append(Paragraph("4. Verification Record", H1))
    story.append(Paragraph(
        "The system was verified end-to-end against the live application:",
        BODY,
    ))
    for ver in [
        "Health check passed; backend and frontend started cleanly.",
        "Six synthetic CVs generated and uploaded through the public API; each was extracted, chunked, scanned and indexed.",
        "A real natural-language query (\u201cFind a Java developer with Spring Boot experience\u201d) returned ranked, cited candidates with match scores.",
        "Document management (list / remove), dashboard statistics, and the AI evaluation run all completed successfully.",
        "Automated test suite: 56 tests passed, covering ingestion, chunking, guardrails, API endpoints, agent pipeline and security gates.",
        "Security checks: CORS restricted to the frontend origin (evil origins are rejected), endpoints enforce auth when a token is configured, rate limits return HTTP 429 with Retry-After.",
    ]:
        story.append(Paragraph(f"\u2022  {ver}", BODY))

    # ---------------------------------------------------------- 5 Screenshots
    story.append(PageBreak())
    story.append(Paragraph("5. Application Walkthrough (Screenshots)", H1))
    story.append(Paragraph(
        "The following pages were captured from the real running application. All candidate "
        "data visible is synthetic. Screenshot \u206003\u2060 shows a live four-agent query "
        "execution with ranked results.",
        BODY,
    ))

    shot_specs: list[tuple[str, str, str]] = [
        ("01-home.png", "Home page",
         "Landing view presenting the agentic workflow, key statistics, a direct query box, "
         "CV upload and the synthetic-data generator."),
        ("02-query-empty.png", "Query page",
         "Natural-language question input for the knowledge base."),
        ("03-query-answer.png", "Live query execution",
         "Ranked, cited answer for \u201cFind a Java developer with Spring Boot experience\u201d "
         "- the Responder returns candidates with match scores and evidence."),
        ("04-documents.png", "Documents page",
         "Manage the ingested CV pool: per-document chunk counts, selection and removal."),
        ("05-dashboard.png", "Dashboard",
         "Ingestion statistics, document-format/section distribution charts and query "
         "performance summary."),
        ("06-evaluation.png", "AI evaluation",
         "Results of the automated pipeline evaluation: pass rate, pass/fail counts and "
         "per-question latency."),
    ]

    for fname, title, cap in shot_specs:
        img_path = SHOTS / fname
        if not img_path.exists():
            continue
        story.append(Paragraph(f"5.{shot_specs.index((fname, title, cap)) + 1}  {title}", H2))
        im = Image(str(img_path), width=160 * mm, height=101 * mm)
        im.hAlign = "CENTER"
        story.append(im)
        story.append(Paragraph(cap, CAP))
        story.append(Spacer(1, 3 * mm))

    # ------------------------------------------------ 6 Quality & safety
    story.append(PageBreak())
    story.append(Paragraph("6. Quality, Reliability & Safety", H1))
    story.append(Paragraph(
        "<b>Error handling.</b> The LLM client distinguishes transient failures (HTTP 408/429/5xx, "
        "timeouts, network errors) which are retried with exponential backoff and jitter - honoring "
        "Retry-After headers - from permanent 4xx failures which are never retried. Failures are "
        "surfaced loudly with clear messages instead of being silently swallowed or replaced with "
        "canned answers.",
        BODY,
    ))
    story.append(Paragraph(
        "<b>Honesty of guardrails.</b> Prompt-injection scanning runs on ingested documents; "
        "tainted content is flagged and surfaced in the UI warnings rather than hidden. "
        "Out-of-scope queries (weather, request to ignore instructions, etc.) are rejected by the "
        "Planner before any retrieval cost is incurred.",
        BODY,
    ))
    story.append(Paragraph(
        "<b>Security posture.</b> CORS is restricted to the frontend origin. The API supports "
        "optional bearer-token authentication (enforced on every endpoint when configured, with "
        "the health check exempt). Rate limiting is applied to query and evaluation endpoints. "
        "Upload sizes are bounded <i>before</i> file contents are read, and filenames are "
        "sanitized against path-traversal attacks.",
        BODY,
    ))
    story.append(Paragraph(
        "<b>Configuration hygiene.</b> Model identifiers, retry budgets, rate limits, scoring "
        "thresholds and CORS origins all live in a single configuration file. No hardcoded "
        "credentials or secrets ship with the project; the frontend uses a bring-your-own-key "
        "model where the user supplies the model-provider key per request.",
        BODY,
    ))

    # --------------------------------------------------------- 7 Evaluation
    story.append(Paragraph("7. AI Evaluation", H1))
    story.append(Paragraph(
        "The built-in evaluation harness runs the pipeline against a curated question set "
        "(covering easy, medium and hard queries) and scores each run. For every question it "
        "records the query type, whether retrieval returned candidates, the top match score, "
        "latency, and whether the answer passed validation. This is a self-grading harness: "
        "an end-to-end run on the demonstration dataset reported a pass rate in the "
        "forties-fifties percent range, with the majority of failures attributable to the "
        "harder out-of-scope and empty-knowledge cases rather than hallucinated content.",
        BODY,
    ))
    story.append(Paragraph(
        "The evaluation results are exported as structured JSON alongside the knowledge base, "
        "enabling repeatable before/after comparison of model, prompting or retrieval changes.",
        BODY,
    ))

    # --------------------------------------- 8 Limitations & challenges
    story.append(Paragraph("8. Limitations & Challenges", H1))
    for lim in [
        "Self-graded evaluation: passing means the pipeline reported in-scope retrieval with valid output; it does not yet use an independent judge model to grade answer correctness or citation grounding. A judge-agent grade is a planned enhancement.",
        "The vector store is a local, in-process ChromaDB instance: state resets on redeploy unless a persistent volume is mounted, and it is tuned for single-worker deployments.",
        "Rate limiting is in-memory and resets on process restart; acceptable for the reference deployment, a shared store would be needed for horizontally scaled services.",
        "Protective model defaults are LOCALHOST-only CORS and empty auth token: a public deployment must explicitly set its frontend origin and choose an auth token. This is documented in the project's deployment notes.",
        "The PLM provider returns variable output-token budgets; large answer payloads occasionally require elevated token limits, which the pipeline now configures explicitly.",
    ]:
        story.append(Paragraph(f"\u2022  {lim}", BODY))
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph(
        "These limitations are scoped to the demonstration goals of this capstone and do not "
        "affect the correctness of the demonstrated agentic-RAG behaviour.",
        BODY,
    ))

    doc.build(story)
    print(f"PDF written: {OUT} ({OUT.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    build()